### ISSUE TITLE
Please add a README

### ISSUE THREAD

**Issue by RickCarlino** [Koden02/PKMN-Fusion#1]
I can sort of see what you're doing from the source code. It looks cool. Can you please add a readme? You're making a pokemon game in FORTH, right?

**Comment by LizardLeliel** [comment]
We're implementing a game with pokemon mechanics on a MUCK, which uses the muf scripting language. So what you said is mostly right; the files in there are currently core battle system code; we're in the process of heavily re-factoring it.

What do you expect to be in the readme? I suspect the description I just gave would be in there but if you feel there any other details that would be helpful, please do tell me, and I'll try to add them into the readme tonight.

**Comment by RickCarlino** [comment]
That answers all my questions!

Is there a public facing URL/port for the MUCK? No worries if its not something you want to share right now. Looks like a fun project.

**Comment by LizardLeliel** [comment]
Certainly, the MUCK has been around for many years now, I and the head programming wizard decided to have code on github just recently especially with our plans to refactor.

We also have a test server for editing code, but it'll be up to the owner of this repository to provide you with.

The public address is pokemonfusion.servegame.org with port 4321. We also have a wiki here: http://pokemonfusion.servegame.org/index.php?title=Main_Page. I'll include both of these on the readme file.
